### ISSUE TITLE
ConnMan: no carrier

### ISSUE THREAD

**Issue by pukkamustard** [dividat/playos#11]
When booting a PlayOS for the first time (or after a user data wipe) scanning for wifi networks with `connmanctl scan wifi` (or from the network initialization code in `controller/server/network.ml`) fails with the error "/net/connman/technology/wifi: No carrier".

The controller detects this and attempts to restart `wpa_supplicant` which however does not immediately resolve the issue. But this "hack" seems to resolve the issue after a reboot.

This seems to be an upstream issue:
https://01.org/jira/browse/CM-670)

See also the Arch Linux wiki: https://wiki.archlinux.org/index.php/ConnMan#Error_/net/connman/technology/wifi:_No_carrier

**Comment by knuton** [comment]
Resolved with a still more ruthless hack in #13.
